name: Copy Folder on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout minstant
        uses: actions/checkout@v2

      - name: Create Target Directory in SaleSure
        run: |
          mkdir -p ../SaleSure/SaleTests

      - name: Copy Folder to SaleSure
        run: |
          # Replace 'tmp' with the actual folder name
          cp -r tmp/* ../SaleSure/SaleTests

        env:
          REPOSITORY_B_TOKEN: ${{ secrets.REPO_B_TOKEN }}
