name: Copy Folder on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout minstant
        uses: actions/checkout@v2
        with:
          repository: codertcet111/minstant
          ref: master

      - name: Come out of minstant
        run: |
          cd ../..

      - name: Checkout SaleSure
        uses: actions/checkout@v2
        with:
          repository: codertcet111/SaleSure
          ref: master
          token: ${{ secrets.REPO_B_TOKEN }}

      - name: Come out of SaleSure
        run: |
          cd ../..

      - name: Create Target Directory in SaleSure
        run: |
          mkdir -p SaleSure/SaleSure/SaleTests

      - name: Copy Folder to SaleSure
        run: |
          cp -r minstant/minstant/tmp/* SaleSure/SaleSure/SaleTests

      - name: Commit and Push Changes to SaleSure
        run: |
          cd SaleSure/SaleSure
          git config user.name "Shubham Actions"
          git config user.email "shubham@mishra.com"
          git add .
          git commit -m "Copy folder from minstant on pull request close"
          git push origin master

        env:
          REPOSITORY_B_TOKEN: ${{ secrets.REPO_B_TOKEN }}
